# Generated by Django 5.2.2 on 2025-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='usn',
            field=models.CharField(default='FAC000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(default='STD000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Unknown Subject', max_length=100),
        ),
    ]
