# Generated by Django 5.2.2 on 2025-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_faculty_usn_student_usn_alter_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='SUBJ001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
    ]
