# Generated by Django 5.2.2 on 2025-07-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
        migrations.AddField(
            model_name='faculty',
            name='current_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback_app.subject'),
        ),
    ]
