# Generated by Django 5.2.2 on 2025-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_remove_faculty_subjects_faculty_current_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='current_subject',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='feedback_app.subject'),
        ),
    ]
