# Generated by Django 5.2.2 on 2025-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_remove_faculty_current_subject_faculty_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
