# Generated by Django 5.2.2 on 2025-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0008_alter_faculty_name_alter_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentfacultymap',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentfacultymap',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentfacultymap',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject_names',
            field=models.TextField(default='Default Subject'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='faculty_name',
            field=models.CharField(default='Unnamed Faculty', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject_name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AddField(
            model_name='studentfacultymap',
            name='faculty_name',
            field=models.CharField(default='Unnamed Faculty', max_length=100),
        ),
        migrations.AddField(
            model_name='studentfacultymap',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=100),
        ),
        migrations.AddField(
            model_name='studentfacultymap',
            name='subject_name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=100),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject_name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='No comments', null=True),
        ),
    ]
