# Generated by Django 5.2.2 on 2025-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0009_remove_faculty_subjects_remove_faculty_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject_names',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subject_name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='section_name',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Unnamed Faculty', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student_name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unnamed Student', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentfacultymap',
            name='student_name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='student_name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Default Subject', max_length=100, unique=True),
        ),
    ]
