# Generated by Django 5.2.2 on 2025-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0010_remove_faculty_subject_names_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.CharField(default='default_faculty', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.CharField(default='default_student', max_length=150),
        ),
    ]
