# Generated by Django 5.2.2 on 2025-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0011_faculty_user_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='feedback_app.subject'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Unnamed Faculty', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
