# Generated by Django 5.2.2 on 2025-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0012_remove_faculty_subject_name_faculty_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='SUB000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Unnamed Subject', max_length=100, unique=True),
        ),
    ]
