# Generated by Django 5.2.2 on 2025-07-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0013_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfacultymap',
            name='subject_name',
        ),
    ]
