# Generated by Django 5.2.2 on 2025-07-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0014_remove_studentfacultymap_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfacultymap',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='studentfacultymap',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentfacultymap',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty'),
        ),
        migrations.AddField(
            model_name='studentfacultymap',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.student'),
        ),
    ]
