# Generated by Django 5.2.2 on 2025-07-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0016_feedbackquestion_remove_feedback_faculty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedbackquestion'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.student'),
        ),
    ]
