# Generated by Django 5.2.2 on 2025-07-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0017_alter_feedback_faculty_alter_feedback_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.subject'),
        ),
    ]
