# Generated by Django 5.2.2 on 2025-07-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0018_alter_feedback_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AddField(
            model_name='feedback',
            name='faculty_name',
            field=models.CharField(default='Unnamed Faculty', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject_name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FeedbackQuestion',
        ),
    ]
