# Generated by Django 5.2.2 on 2025-07-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0019_remove_feedback_question_remove_feedback_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='How was the teaching?')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.student'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.subject'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='No comments', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedbackquestion'),
        ),
    ]
