# Generated by Django 5.2.2 on 2025-07-28 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0020_feedbackquestion_remove_feedback_faculty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Faculty Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(to='feedback_app.subject'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.CharField(default='faculty_user', max_length=150),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='usn',
            field=models.CharField(default='FAC123', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(default='student_user', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default='STU123', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfacultymap',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty'),
        ),
        migrations.AlterField(
            model_name='studentfacultymap',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='SUB001', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Untitled Subject', max_length=100),
        ),
    ]
