# Generated by Django 5.2.2 on 2025-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0022_student_semester_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='semester',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
