# Generated by Django 5.2.2 on 2025-07-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0023_faculty_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='1', max_length=10)),
                ('section', models.CharField(default='A', max_length=10)),
                ('year', models.CharField(default='2025', max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.subject')),
            ],
        ),
    ]
