# Generated by Django 5.2.2 on 2025-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0024_facultysubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultysubject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='faculty_name',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='subject_name',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
