# Generated by Django 5.2.2 on 2025-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0025_remove_facultysubject_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultysubject',
            name='faculty_name',
            field=models.CharField(default='Unknown Faculty', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='subject_name',
            field=models.CharField(default='Unknown Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='student_name',
            field=models.CharField(default='Unknown Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject_name',
            field=models.CharField(default='Unknown Subject', max_length=100),
        ),
    ]
