# Generated by Django 5.2.2 on 2025-07-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0026_alter_facultysubject_faculty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubject',
            name='faculty_id',
            field=models.CharField(default='F001', max_length=20),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='subject_id',
            field=models.CharField(default='SUB001', max_length=20),
        ),
    ]
