# Generated by Django 5.2.2 on 2025-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0027_facultysubject_faculty_id_facultysubject_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultysubject',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='subject_id',
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='faculty_name',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='subject_name',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='student_name',
            field=models.CharField(default='Unnamed Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject_name',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
    ]
