# Generated by Django 5.2.2 on 2025-07-29 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0029_facility_facilityfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEndQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseEndFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.student')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.courseendquestion')),
            ],
        ),
    ]
