# Generated by Django 5.2.2 on 2025-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0030_courseendquestion_courseendfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='generated_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='generated_userid',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
