# Generated by Django 5.2.2 on 2025-08-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0031_student_generated_password_student_generated_userid'),
    ]

    operations = [
        
    ]
