# Generated by Django 5.2.2 on 2025-08-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0032_rename_name_facility_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='text',
        ),
    ]
